databases:
  - name: pro1
    plan: free
    databaseName: mysitedb
    user: mysiteuser

services:
  - type: web
    plan: free
    name: pro1
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pro1
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4